- include_role: {name: corpusops.roles/docker_compose_service}
  vars:
    _docker_compose_service:
      project: "{{cops_squid_compose_project}}"
      state: "{{cops_squid_started_state}}"
      working_directory: "{{cops_squid_hostdir}}"
      stdout: "{{cops_squid_stdout}}"
      stderr: "{{cops_squid_stderr}}"
  tags: [service_start]
- shell: |-
    set -ex
    cd "{{cops_squid_hostdir}}"
    docker-compose -p {{cops_squid_compose_project}} up -d
  tags: [service_dockercompose_restart]
