---
- name: Create directories
  file:
    path: "{{cops_squid_versioned_hostdir}}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{cops_squid_setup_path}}/"
  when: item.state == 'directory'
- name: Template files
  template:
    src: '{{ item.src }}'
    dest: "{{cops_squid_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
    trim_blocks: false
  with_filetree: "{{cops_squid_setup_path}}/"
  when:
  - "item.state == 'file'"
  - "not item.path|regex_search('\\.frep$|conf.d|rclone.*\\.py')"
- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: "{{cops_squid_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_filetree: "{{cops_squid_setup_path}}/"
  when:
  - "item.state == 'file'"
  - "     item.path|regex_search('\\.frep$|conf.d|rclone.*\\.py')"
- loop: "{{cops_squid_users|dict2items}}"
  community.general.htpasswd:
    path: "{{cops_squid_passwdfile}}"
    name: "{{item.key}}"
    password: '{{item.value}}'
    owner: 33
    group: 33
    mode: 0640
- copy:
    force: true
    content: "{{cops_squid_conf_ldap_password}}"
    dest: "{{cops_squid_versioned_hostdir}}/conf/ldap_password.in"
    mode: "0640"
    owner: 33
    group: 33
- include_role: {name: corpusops.roles/ms_iptables_registrations}
  tags: [ms_iptables_registrations]
